<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0 (Python 3.10.10 on win32)" generated="2024-05-26T21:21:31.847886" rpa="false" schemaversion="5">
<suite id="s1" name="Test-Mobile" source="C:\Android\Mobile-Automation-RobotFramework\Suites\test-mobile.robot">
<test id="s1-t1" name="User should be able to login with valid credential" line="49">
<kw name="Open Flight Application">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-05-26T21:21:34.674279" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x00000213CE787190&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-26T21:21:36.724606" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x00000213CE787640&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-26T21:21:38.748395" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x00000213CE787D30&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-05-26T21:21:40.801422" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-05-26T21:21:40.801422" elapsed="0.010419">No application is open</status>
</kw>
<msg time="2024-05-26T21:21:40.815998" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-05-26T21:21:40.817223" level="FAIL">MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=4237): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x00000213CE787F40&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</msg>
<arg>remote_url=${REMOTE_URL}</arg>
<arg>platformName=${PLATFORM_NAME}</arg>
<arg>platformVersion=${PLATFORM_VERSION}</arg>
<arg>deviceName=${DEVICE NAME}</arg>
<arg>appPackages=${APP_PACKAGE}</arg>
<arg>appActivity=${APP_ACTIVITY}</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-05-26T21:21:32.557635" elapsed="8.262831">MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=4237): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x00000213CE787F40&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</kw>
<status status="FAIL" start="2024-05-26T21:21:32.557635" elapsed="8.263900">MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=4237): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x00000213CE787F40&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</kw>
<kw name="Verify Homescreen">
<status status="NOT RUN" start="2024-05-26T21:21:40.821535" elapsed="0.001055"/>
</kw>
<kw name="Click Sign in Button on Home Screen">
<status status="NOT RUN" start="2024-05-26T21:21:40.822590" elapsed="0.000000"/>
</kw>
<status status="FAIL" start="2024-05-26T21:21:32.542004" elapsed="8.281646">MaxRetryError: HTTPSConnectionPool(host='127.0.0.1', port=4237): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x00000213CE787F40&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))</status>
</test>
<status status="FAIL" start="2024-05-26T21:21:31.847886" elapsed="8.979095"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test-Mobile">Test-Mobile</stat>
</suite>
</statistics>
<errors>
<msg time="2024-05-26T21:21:34.674279" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x00000213CE787190&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-26T21:21:36.724606" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x00000213CE787640&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-26T21:21:38.748395" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPSConnection object at 0x00000213CE787D30&gt;: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /wd/hub/session</msg>
<msg time="2024-05-26T21:21:40.815998" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
